doctrine:
    dbal:
        schema_filter: ~^(?!event)~ # this will ignore broadway event store table
        # Using explicit pdo_mysql driver - do not rely on URL scheme
        driver: pdo_mysql
        host: '%env(string:DATABASE_HOST)%'
        port: '%env(int:DATABASE_PORT)%'
        dbname: '%env(string:DATABASE_NAME)%'
        user: '%env(string:DATABASE_USER)%'
        password: '%env(string:DATABASE_PASSWORD)%'
        charset: utf8mb4
        server_version: '8.0.33'
        use_savepoints: true
        types:
          uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
          datetime_immutable: App\Shared\Infrastructure\Persistence\Doctrine\Types\DateTimeType
          email: App\Shared\Infrastructure\Persistence\Doctrine\Types\EmailType
          hashed_password: App\Shared\Infrastructure\Persistence\Doctrine\Types\HashedPasswordType
        mapping_types:
          uuid_binary: binary
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/App/User'
                prefix: 'App\User'
                alias: App
