apiVersion: v2
appVersion: "1.0"
description: DDD CQRS boilerplate
name: symfony-5-es-cqrs-boilerplate
version: 0.1.0
type: application
dependencies:
  - name: rabbitmq
    version: 6.25.2
    repository: https://charts.bitnami.com/bitnami
    conditions: rabbitmq.selfHosted
  - name: traefik
    version: 28.3.0
    repository: https://traefik.github.io/charts
    conditions: traefik.selfHosted
  - name: mysql
    version: 11.1.17
    repository: https://charts.bitnami.com/bitnami
    conditions: mysql.selfHosted
  - name: elasticsearch
    version: 7.6.2
    repository: https://helm.elastic.co
    conditions: elasticsearch.selfHosted